spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari.auto-commit: false
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy #Envers ?? ???
      hibernate:
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 5000
        format_sql: true
        highlight_sql: true
        use_sql_comments: false
        show_sql: true
        connection.provider_disables_autocommit: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        default_batch_fetch_size: 5
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath*:data_*.sql

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    #logging.level.ROOT=INFO
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    # Enable logging for HikariCP to verify that it is used
    com.zaxxer.hikari.HikariConfig: TRACE
    com.zaxxer.hikari: TRACE






---
# multi-data-source
primary:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  driver-class-name: org.h2.Driver
  hikari:
    pool-name: primary
    auto-commit: false
    connection-timeout: 50000
    idle-timeout: 300000
    max-lifetime: 900000
    maximum-pool-size: 8
    minimum-idle: 8
    connection-test-query: SELECT 1
secondary:
  url: jdbc:postgresql://localhost:5432/testdb
  username: testuser
  password: testpass  # ???? ??
  driver-class-name: org.postgresql.Driver
  hikari:
    pool-name: secondary
    auto-commit: false
    connection-timeout: 100000
    idle-timeout: 300000
    max-lifetime: 900000
    maximum-pool-size: 8
    minimum-idle: 8
    connection-test-query: SELECT 1





