package jpa.practice.relationship.useful_transient.entity.v3_using_formula;

import jakarta.persistence.*;
import jpa.practice.relationship.onetoone.entity.Member;
import org.hibernate.annotations.Formula;

@Entity
public class OrderV3 {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private int quantity;
    private double unitPrice;


    /**
     * SQL 식을 사용하여 총 금액 계산.
     * totalAmount 컬럼은 생성되지 않는다.
     * [Hibernate]
     *     create table orderv3 (
     *         quantity integer not null,
     *         unit_price float(53) not null,
     *         id bigint generated by default as identity,
     *         primary key (id)
     *     )
     */
    @Formula("quantity * unit_price")
    private double totalAmount;

    protected OrderV3() {}

    public OrderV3(int quantity, double unitPrice) {
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (this == obj) return true;
        if(!(obj instanceof Member other)) return false;

        return id != null && id.equals(other.getId());
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return "OrderV3{" + "id=" + id + ", quantity=" + quantity + ", unitPrice=" + unitPrice + '}' + "totalAmount=" + totalAmount;
    }

}